global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'fabric-orderers'
    static_configs:
      - targets:
          - orderer.example.com:9443

  - job_name: 'fabric-peers'
    static_configs:
      - targets:
          - peer0.org1.example.com:9444
          - peer0.org2.example.com:9445

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - localhost:9090

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']

    metric_relabel_configs:

      - source_labels: [name]
        regex: ''
        action: drop

      - regex: 'container_label_com_docker_compose_(config_hash|container_number|depends_on|image|oneoff|project_config_files|project_working_dir|version)'
        action: labeldrop

      - regex: 'container_label_org_opencontainers_image_(created|description|licenses|ref_name|revision|source|title|url)'
        action: labeldrop

      - regex: 'container_label_(maintainer|restartcount)'
        action: labeldrop

